### ISSUE TITLE
1.3 Update Please!

### ISSUE THREAD

**Issue by AustinTX1985** [Dinnerbone/BukkitFullOfMoon#3]
Is there any way that someone can either take over this project or get in touch with the creator to update this to 1.3? I would love to use this for my server, but am not able to due to the lack of a jar file and the need for an update!

**Comment by SKevo18** [comment]
After 7 years, you finally found a sould to reply to you. It is kinda akward to reply that late, but it feels very satisfying to reply on post, that is that old. Very insidious. Minecraft is now 1.13.x, not just 1.3. And I can tell you, a lot of new world generators were made. Perfect. 

I wonder if someone will actually read this though...

**Comment by GewoonLeonYT** [comment]
Of course someone is reading. Someone always reads this stuff.

**Comment by SKevo18** [comment]
Excellent!

**Comment by truelossless** [comment]
Don't worry, I'll reply in 7 years to let you know we are in 1.30

**Comment by czychuuu** [comment]
1.13 was released 6 years ago crazy
